#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('Hitaki', '0.0')
from gi.repository import Hitaki

target_type = Hitaki.EfwProtocol
props = ()
methods = (
    'transmit_request',
    'receive_response',
    'transaction',
)
vmethods = (
    'do_transmit_request',
    'do_get_seqnum',
    'do_responded',
)
signals = (
    'responded',
)

if not test_object(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
