#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

import gi
gi.require_version('Hitaki', '0.0')
from gi.repository import Hitaki

from helper import test_functions

types = {
    Hitaki.AlsaFirewireError: (
        'quark',
        'to_label',
    ),
    Hitaki.EfwProtocolError: (
        'quark',
        'to_label',
    ),
}

for target_type, functions in types.items():
    if not test_functions(target_type, functions):
        exit(ENXIO)
