#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('Hitaki', '0.0')
from gi.repository import Hitaki

alsa_firewire_type_enumerations = (
    'DICE',
    'FIREWORKS',
    'BEBOB',
    'OXFW',
    'DIGI00X',
    'TASCAM',
    'MOTU',
    'FIREFACE',
)
types = {
    Hitaki.AlsaFirewireType: alsa_firewire_type_enumerations,
}

for obj, types in types.items():
    for t in types:
        if not hasattr(obj, t):
            print('Enumerator {0} is not produced.'.format(t))
            exit(ENXIO)
