#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('Hitaki', '0.0')
from gi.repository import Hitaki

target_type = Hitaki.MotuRegisterDsp
props = ()
methods = (
    'read_parameter',
    'read_byte_meter',
)
vmethods = (
    'do_read_parameter',
    'do_read_byte_meter',
    'do_changed',
)
signals = (
    'changed',
)

if not test_object(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
