#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('Hitaki', '0.0')
from gi.repository import Hitaki

target = Hitaki.SndMotu()
props = (
    'unit-type',
    'card-id',
    'node-device',
    'is-locked',
    'guid',
    'is-disconnected',
)
methods = (
    'open',
    'lock',
    'unlock',
    'create_source',
    'new',
    'read_parameter',
    'read_byte_meter',
    'read_float_meter',
)
vmethods = (
    #'do_notified',
    #'do_changed',
)
signals = (
    #'notified',
    #'changed',
)

if not test(target, props, methods, vmethods, signals):
    exit(ENXIO)
