#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('Hitaki', '0.0')
from gi.repository import Hitaki

target_type = Hitaki.SndUnit
props = (
    'unit-type',
    'card-id',
    'node-device',
    'is-locked',
    'guid',
    'is-disconnected',
)
methods = (
    'open',
    'lock',
    'unlock',
    'create_source',
    'new',
)
vmethods = (
    'do_open',
    'do_lock',
    'do_unlock',
    'do_create_source',
)
signals = ()

if not test(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
