#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test

import gi
gi.require_version('Hitaki', '0.0')
from gi.repository import Hitaki

target = Hitaki.SndEfw()
props = (
    'unit-type',
    'card-id',
    'node-device',
    'is-locked',
    'guid',
    'is-disconnected',
)
methods = (
    'open',
    'lock',
    'unlock',
    'create_source',
    'new',
    'request',
    'transaction',
)
vmethods = (
    #'do_responded',
)
signals = (
    #'responded',
)

if not test(target, props, methods, vmethods, signals):
    exit(ENXIO)
