#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('Hitaki', '0.0')
from gi.repository import Hitaki

target_type = Hitaki.SndEfw
props = (
    # From interface.
    'unit-type',
    'card-id',
    'node-device',
    'is-locked',
    'guid',
    'is-disconnected',
)
methods = (
    'new',
    # From interfaces.
    'open',
    'lock',
    'unlock',
    'create_source',
    'transmit_request',
    'receive_response',
    'transaction',
)
vmethods = (
    # From interfaces.
    'do_open',
    'do_lock',
    'do_unlock',
    'do_create_source',
    'do_transmit_request',
    'do_get_seqnum',
    'do_responded',
)
signals = (
    # From interface.
    'responded',
)

if not test_object(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
