#!/usr/bin/env python3

from sys import exit
from errno import ENXIO

from helper import test_object

import gi
gi.require_version('Hitaki', '0.0')
from gi.repository import Hitaki

target_type = Hitaki.TimestampedQuadletNotification
props = ()
methods = ()
vmethods = ()
signals = (
    'notified-at',
)

if not test_object(target_type, props, methods, vmethods, signals):
    exit(ENXIO)
